CREATE TABLE ENROLLEE (
  LOGIN NVARCHAR(20) PRIMARY KEY NOT NULL ,
  PASSWORD NVARCHAR(20) NOT NULL ,
  NAME VARCHAR(20) NOT NULL ,
  SURNAME VARCHAR(20) NOT NULL
);
CREATE TABLE SUBJECT (
  ID INT PRIMARY KEY NOT NULL ,
  NAME NVARCHAR(20) NOT NULL
);
CREATE TABLE DEPARTMENT (
  NAME NVARCHAR(20) PRIMARY KEY NOT NULL ,
  SUBJECT_1 INT NOT NULL ,
  SUBJECT_2 INT NOT NULL ,
  SUBJECT_3 INT NOT NULL ,
  MAX_COUNT INT NOT NULL ,
  FOREIGN KEY (SUBJECT_1) REFERENCES SUBJECT(ID) ,
  FOREIGN KEY (SUBJECT_2) REFERENCES SUBJECT(ID) ,
  FOREIGN KEY (SUBJECT_3) REFERENCES SUBJECT(ID)
);
CREATE TABLE APPLICATION (
  ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL ,
  STUDENT_ID NVARCHAR(20) NOT NULL ,
  NAME_DEP NVARCHAR(20) NOT NULL ,
  SUBJECT_1 INT NOT NULL ,
  SUBJECT_2 INT NOT NULL ,
  SUBJECT_3 INT NOT NULL ,
  AVERAGE_MARK DECIMAL NOT NULL ,
  STATUS NVARCHAR(20) DEFAULT 'PROCESSING',
  RESULT NVARCHAR(20) ,
  CHECK (AVERAGE_MARK <= 5 AND AVERAGE_MARK >= 3) ,
  CHECK (STATUS IN('OK', 'REJECTED', 'PROCESSING')) ,
  FOREIGN KEY (STUDENT_ID) REFERENCES ENROLLEE(LOGIN) ,
  FOREIGN KEY (NAME_DEP) REFERENCES DEPARTMENT(NAME) ,
  FOREIGN KEY (SUBJECT_1) REFERENCES SUBJECT(ID) ,
  FOREIGN KEY (SUBJECT_2) REFERENCES SUBJECT(ID) ,
  FOREIGN KEY (SUBJECT_3) REFERENCES SUBJECT(ID)
);
INSERT INTO ENROLLEE (LOGIN, PASSWORD, NAME, SURNAME) VALUES ('kazachkova.e.s', 'balda', 'Ekaterina', 'Kazachkova');